server:             '0.0.0.0'
show_errors:        1
template:           'template_toolkit'
error_template:     'error'
default_mime_type:  'text/plain'
logger:             'file'
logger_format:      '%t [%L] %m'

